const coffees = [
  {
    imgSrc: "../images/Coffee/Espresso.png",
    mkTitle: "еспресо",
    enTitle: "espresso",
    price: "60.00",
  },
  {
    imgSrc: "../images/Coffee/Prodolzheno.png",
    mkTitle: "продолжено еспресо",
    enTitle: "long espresso",
    price: "60.00",
  },
  {
    imgSrc: "../images/Coffee/Makijato.png",
    mkTitle: "макијато",
    enTitle: "macchiato",
    price: "70.00",
  },
  {
    imgSrc: "../images/Coffee/MaloMakijato.png",
    mkTitle: "мало макијато",
    enTitle: "short macchiato",
    price: "60.00",
  },
  {
    imgSrc: "../images/Coffee/Freddo.png",
    mkTitle: "фредо еспресо",
    enTitle: "fredo espresso",
    price: "70.00",
  },
  {
    imgSrc: "../images/Coffee/Latte.png",
    mkTitle: "лате макијато",
    enTitle: "latte macchiato",
    price: "80.00",
  },
  {
    imgSrc: "../images/Coffee/LatteVkus.png",
    mkTitle: "лате макијато со вкус",
    enTitle: "latte macchiato flavor",
    price: "90.00",
  },
  {
    imgSrc: "../images/Coffee/Kapuchino.png",
    mkTitle: "капучино",
    enTitle: "capuccino",
    price: "80.00",
  },
  {
    imgSrc: "../images/Coffee/Mafijashko.png",
    mkTitle: "мафијашко",
    enTitle: "mafijasko",
    price: "70.00",
  },
  {
    imgSrc: "../images/Coffee/LadnoMakijato.png",
    mkTitle: "ладно макијато",
    enTitle: "cold macchiato",
    price: "70.00",
  },
  {
    imgSrc: "../images/Coffee/Nescafe.png",
    mkTitle: "нескафе",
    enTitle: "nescafe",
    price: "80.00",
  },
  {
    imgSrc: "../images/Coffee/NescafePopareno.png",
    mkTitle: "попаренo нескафе",
    enTitle: "steamed nescafe",
    price: "60.00",
  },
  {
    imgSrc: "../images/Coffee/hotChocolate.png",
    mkTitle: "топло чоколадо",
    enTitle: "hot chocolate",
    price: "100.00",
  },
  {
    imgSrc: "../images/Coffee/hotChocolatePlazma.png",
    mkTitle: "топло чоколадо плазма",
    enTitle: "hot chocolate plazma",
    price: "110.00",
  },
  {
    imgSrc: "../images/Coffee/hotChocolateOreo.png",
    mkTitle: "топло чоколадо со орео",
    enTitle: "hot chocolate with oreo",
    price: "110.00",
  },
  {
    imgSrc: "../images/Coffee/Kakao.png",
    mkTitle: "какао",
    enTitle: "cocoa",
    price: "70.00",
  },
  {
    imgSrc: "../images/Coffee/KakaoMleko.png",
    mkTitle: "какао со млеко",
    enTitle: "cocoa with milk",
    price: "80.00",
  },
  {
    imgSrc: "../images/Coffee/EspressoDecaf.png",
    mkTitle: "безкофеинско еспресо",
    enTitle: "decaffeinated espresso",
    price: "70.00",
  },
];
const nonAlhoholic = [
  {
    imgSrc: "../images/Sodas/CocaCola.png",
    mkTitle: "кока кола",
    enTitle: "coca cola",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/CocaColaZero.png",
    mkTitle: "кока кола зеро",
    enTitle: "coca cola zero",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/Schweppes.png",
    mkTitle: "швепс",
    enTitle: "schweppes",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/SchweppesTangerina.png",
    mkTitle: "швепс танџерина",
    enTitle: "schweppes tangerine",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/SchweppesTonic.png",
    mkTitle: "швепс тоник",
    enTitle: "schweppes tonic",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/Fanta.png",
    mkTitle: "фанта",
    enTitle: "fanta",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/FantaTropical.png",
    mkTitle: "фанта тропикал",
    enTitle: "fanta tropical",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/FantaShokata.png",
    mkTitle: "фанта шоката",
    enTitle: "fanta shokata",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/Sprite.png",
    mkTitle: "спрајт",
    enTitle: "sprite",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/Pepsi.png",
    mkTitle: "пепси",
    enTitle: "pepsi",
    price: "50.00",
  },
  {
    imgSrc: "../images/Sodas/PepsiZero.png",
    mkTitle: "пепси зеро",
    enTitle: "pepsi zero",
    price: "50.00",
  },
  {
    imgSrc: "../images/Sodas/Gazoza.png",
    mkTitle: "газоза",
    enTitle: "gazoza",
    price: "50.00",
  },
  {
    imgSrc: "../images/Sodas/7up.png",
    mkTitle: "севен ап",
    enTitle: "seven up",
    price: "50.00",
  },
  {
    imgSrc: "../images/Sodas/Mirinda.png",
    mkTitle: "миринда",
    enTitle: "mirinda",
    price: "50.00",
  },
  {
    imgSrc: "../images/Sodas/Cockta.png",
    mkTitle: "кокта",
    enTitle: "cocta",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/PellegrinoKalinka.png",
    mkTitle: "сан пелегрино калинка - портокал",
    enTitle: "san pellegrino melograno & arancia",
    price: "90.00",
  },
  {
    imgSrc: "../images/Sodas/PellegrinoMenta.png",
    mkTitle: "сан пелегрино лимон - мента",
    enTitle: "san pellegrino limone & menta",
    price: "90.00",
  },
  {
    imgSrc: "../images/Sodas/PellegrinoLimon.png",
    mkTitle: "сан пелегрино лимоната",
    enTitle: "san pellegrino limonata",
    price: "90.00",
  },
  {
    imgSrc: "../images/Sodas/RedBull.png",
    mkTitle: "ред бул",
    enTitle: "red bull",
    price: "150.00",
  },
  {
    imgSrc: "../images/Sodas/tea.png",
    mkTitle: "чај",
    enTitle: "tea",
    price: "60.00",
  },
  {
    imgSrc: "../images/Sodas/Nektarchinja.png",
    mkTitle: "нектар",
    enTitle: "nectar",
    price: "80.00",
  },
  {
    imgSrc: "../images/Sodas/Mango.png",
    mkTitle: "нектар манго",
    enTitle: "nectar mango",
    price: "80.00",
  },
  {
    imgSrc: "../images/Sodas/Cedevita.png",
    mkTitle: "цедевита",
    enTitle: "cedevita",
    price: "50.00",
  },
  {
    imgSrc: "../images/Sodas/OrangeJuice.png",
    mkTitle: "цеден портокал",
    enTitle: "squeezed orange",
    price: "100.00",
  },
  {
    imgSrc: "../images/Sodas/LemonJuice.png",
    mkTitle: "цеден лимон",
    enTitle: "squeezed lemon",
    price: "80.00",
  },
  {
    imgSrc: "../images/Sodas/MixOrangeLemon.png",
    mkTitle: "цеден микс пл",
    enTitle: "squeezed mix",
    price: "120.00",
  },
];
const waters = [
  {
    imgSrc: "../images/Waters/PelisterkaNegazirana.png",
    mkTitle: "пелистерка",
    enTitle: "pelisterka",
    price: "50.00",
  },
  {
    imgSrc: "../images/Waters/PelisterkaGazirana.png",
    mkTitle: "пелистерка газирана",
    enTitle: "pelisterka sparkling",
    price: "50.00",
  },
  {
    imgSrc: "../images/Waters/Rosa.png",
    mkTitle: "роса",
    enTitle: "rosa",
    price: "50.00",
  },
  {
    imgSrc: "../images/Waters/KnjazWater.png",
    mkTitle: "књаз милош",
    enTitle: "knjaz milos",
    price: "50.00",
  },
];
const beers = [
  {
    imgSrc: "../images/Beer/skopskoOriginal.png",
    mkTitle: "скопско",
    enTitle: "skopsko",
    price: "90.00",
  },
  {
    imgSrc: "../images/Beer/skopskoSmooth.png",
    mkTitle: "скопско смут",
    enTitle: "skopsko smooth",
    price: "90.00",
  },
  {
    imgSrc: "../images/Beer/heineken.png",
    mkTitle: "хајнекен",
    enTitle: "heineken",
    price: "130.00",
  },
  {
    imgSrc: "../images/Beer/amstel.png",
    mkTitle: "амстел",
    enTitle: "amstel",
    price: "100.00",
  },
  {
    imgSrc: "../images/Beer/zlatenDab.png",
    mkTitle: "златен даб",
    enTitle: "zlaten dab",
    price: "90.00",
  },
  {
    imgSrc: "../images/Beer/becks.png",
    mkTitle: "бекс",
    enTitle: "beck's",
    price: "80.00",
  },
  {
    imgSrc: "../images/Beer/stella.png",
    mkTitle: "стела",
    enTitle: "stella",
    price: "120.00",
  },
  {
    imgSrc: "../images/Beer/tuborg.png",
    mkTitle: "туборг",
    enTitle: "tuborg",
    price: "100.00",
  },
  {
    imgSrc: "../images/Beer/mugBig.png",
    mkTitle: "скопско кригла (0.5l)",
    enTitle: "skopsko mug",
    price: "100.00",
  },
  {
    imgSrc: "../images/Beer/mugSmall.png",
    mkTitle: "скопско кригла (0.33l)",
    enTitle: "skopsko small mug",
    price: "90.00",
  },
];
const liquors = [
  {
    imgSrc: "../images/Liquors/Konjak.png",
    mkTitle: "коњак",
    enTitle: "cognac",
    price: "80.00",
  },
  {
    imgSrc: "../images/Liquors/Stock.png",
    mkTitle: "шток",
    enTitle: "stock",
    price: "90.00",
  },
  {
    imgSrc: "../images/Liquors/Vigor.png",
    mkTitle: "водка вигор",
    enTitle: "vodka vigor",
    price: "80.00",
  },
  {
    imgSrc: "../images/Liquors/Smirnoff.png",
    mkTitle: "водка смирноф",
    enTitle: "vodka smirnoff",
    price: "100.00",
  },
  {
    imgSrc: "../images/Liquors/GreyGoose.png",
    mkTitle: "греј гус",
    enTitle: "grey goose",
    price: "250.00",
  },
  {
    imgSrc: "../images/Liquors/SaxGin.png",
    mkTitle: "џин сакс",
    enTitle: "gin sax",
    price: "80.00",
  },
  {
    imgSrc: "../images/Liquors/GordonsGin.png",
    mkTitle: "џин гордонс",
    enTitle: "gin gordon's",
    price: "100.00",
  },
  {
    imgSrc: "../images/Liquors/GordonsPink.png",
    mkTitle: "гордонс пинк",
    enTitle: "gordon's pink",
    price: "120.00",
  },
  {
    imgSrc: "../images/Liquors/BombayGin.png",
    mkTitle: "џин бомбај",
    enTitle: "gin bombay",
    price: "100.00",
  },
  {
    imgSrc: "../images/Liquors/HendricksGin.png",
    mkTitle: "хендрикс џин",
    enTitle: "gin hendrick's",
    price: "250.00",
  },
  {
    imgSrc: "../images/Liquors/RumBadel.png",
    mkTitle: "рум бадел",
    enTitle: "badel rum",
    price: "90.00",
  },
  {
    imgSrc: "../images/Liquors/BacardiRum.png",
    mkTitle: "рум бакарди",
    enTitle: "bacardi rum",
    price: "110.00",
  },
  {
    imgSrc: "../images/Liquors/CapetanMorgan.png",
    mkTitle: "рум кептен морган",
    enTitle: "captain morgan rum",
    price: "100.00",
  },
  {
    imgSrc: "../images/Liquors/Jeger.png",
    mkTitle: "јегер",
    enTitle: "jagermeister",
    price: "130.00",
  },
  {
    imgSrc: "../images/Liquors/Pelinkovac.png",
    mkTitle: "пелинковец",
    enTitle: "pelinkovac",
    price: "80.00",
  },
  {
    imgSrc: "../images/Liquors/Baileys.png",
    mkTitle: "бејлис",
    enTitle: "baileys",
    price: "100.00",
  },
  {
    imgSrc: "../images/Liquors/Martini.png",
    mkTitle: "мартини",
    enTitle: "martini",
    price: "90.00",
  },
  {
    imgSrc: "../images/Liquors/Tsantali.png",
    mkTitle: "узо тсантали",
    enTitle: "ouzo tsantali",
    price: "80.00",
  },
  {
    imgSrc: "../images/Liquors/Plomari.png",
    mkTitle: "пломари узо",
    enTitle: "plomari ouzo",
    price: "90.00",
  },
  {
    imgSrc: "../images/Liquors/brandy.png",
    mkTitle: "вињак",
    enTitle: "brandy",
    price: "80.00",
  },
  {
    imgSrc: "../images/Liquors/tequilaMendoza.png",
    mkTitle: "текила",
    enTitle: "tequila",
    price: "70.00",
  },
  {
    imgSrc: "../images/Liquors/campari.png",
    mkTitle: "кампари",
    enTitle: "campari",
    price: "80.00",
  },
  {
    imgSrc: "../images/Liquors/jackDaniels.png",
    mkTitle: "џек даниелс",
    enTitle: "jack daniels",
    price: "200.00",
  },
  {
    imgSrc: "../images/Liquors/jimBeam.png",
    mkTitle: "џим бим",
    enTitle: "jim beam",
    price: "180.00",
  },
  {
    imgSrc: "../images/Liquors/jameson.png",
    mkTitle: "џејмсон",
    enTitle: "jameson",
    price: "180.00",
  },
  {
    imgSrc: "../images/Liquors/ballantines.png",
    mkTitle: "балантајн",
    enTitle: "ballantines",
    price: "150.00",
  },
  {
    imgSrc: "../images/Liquors/redLabel.png",
    mkTitle: "џони вокер",
    enTitle: "johnie walker",
    price: "180.00",
  },
  {
    imgSrc: "../images/Liquors/blackLabel.png",
    mkTitle: "џ. блек",
    enTitle: "johnie black",
    price: "250.00",
  },
  {
    imgSrc: "../images/Liquors/chivas.png",
    mkTitle: "чивас",
    enTitle: "chivas",
    price: "250.00",
  },
  {
    imgSrc: "../images/Liquors/j&b.png",
    mkTitle: "Џ&Б",
    enTitle: "J&B",
    price: "150.00",
  },
  {
    imgSrc: "../images/Liquors/vigorWithJuice.png",
    mkTitle: "сечена водка",
    enTitle: "vodka w juice",
    price: "100.00",
  },
  {
    imgSrc: "../images/Liquors/smirnoffWithJuice.png",
    mkTitle: "сечен смирноф",
    enTitle: "smirnoff w juice",
    price: "110.00",
  },
  {
    imgSrc: "../images/Liquors/saxTonic.png",
    mkTitle: "џин тоник",
    enTitle: "gin tonic",
    price: "100.00",
  },
  {
    imgSrc: "../images/Liquors/rumCocaCola.png",
    mkTitle: "сечен рум",
    enTitle: "rum w juice",
    price: "90.00",
  },
  {
    imgSrc: "../images/Liquors/campariTonic.png",
    mkTitle: "кампари тоник",
    enTitle: "campari tonic",
    price: "110.00",
  },
  {
    imgSrc: "../images/Liquors/deepSeaBlueShot.png",
    mkTitle: "шат",
    enTitle: "shot",
    price: "100.00",
  },
];
const wines = [
  {
    imgSrc: "../images/Wines/MaloTraminec.png",
    mkTitle: "александрија траминец 0.2",
    enTitle: "alexandria traminec",
    price: "150.00",
  },
  {
    imgSrc: "../images/Wines/MaloBelo.png",
    mkTitle: "александрија бело 0.2",
    enTitle: "alexandria white",
    price: "150.00",
  },
  {
    imgSrc: "../images/Wines/MaloTemjanika.png",
    mkTitle: "александрија темјаника 0.2",
    enTitle: "alexandria temjanika",
    price: "150.00",
  },
  {
    imgSrc: "../images/Wines/MaloRoze.png",
    mkTitle: "александрија розе 0.2",
    enTitle: "alexandria rose",
    price: "150.00",
  },
  {
    imgSrc: "../images/Wines/MaloCrveno.png",
    mkTitle: "александрија црвено 0.2",
    enTitle: "alexandria red",
    price: "150.00",
  },
  {
    imgSrc: "../images/Wines/MaloTga.png",
    mkTitle: "т'га за југ 0.2",
    enTitle: "t'ga za jug",
    price: "150.00",
  },
  {
    imgSrc: "../images/Wines/tikvesTraminec.png",
    mkTitle: "александрија траминец 0.7",
    enTitle: "alexandria traminec",
    price: "600.00",
  },
  {
    imgSrc: "../images/Wines/alexandriaWhite.png",
    mkTitle: "александрија бело 0.7",
    enTitle: "alexandria white",
    price: "600.00",
  },
  {
    imgSrc: "../images/Wines/tikvesTemjanika.png",
    mkTitle: "александрија темјаника 0.7",
    enTitle: "alexandria temjanika",
    price: "600.00",
  },
  {
    imgSrc: "../images/Wines/alexandriaRoze.png",
    mkTitle: "александрија розе 0.7",
    enTitle: "alexandria rose",
    price: "600.00",
  },
  {
    imgSrc: "../images/Wines/alexandriaRed.png",
    mkTitle: "александрија црвено 0.7",
    enTitle: "alexandria red",
    price: "600.00",
  },
  {
    imgSrc: "../images/Wines/alexandriaTga.png",
    mkTitle: "т'га за југ 0.7",
    enTitle: "t'ga za jug",
    price: "600.00",
  },
];
const cocktails = [
  {
    imgSrc: "../images/Cocktails/pinaColada.png",
    title: "Pina colada",
    ingredients: ["White rum", "Coconut purée", "Pineapple juice"],
    price: "180.00",
  },
  {
    imgSrc: "../images/Cocktails/blueLagoon.png",
    title: "Blue lagoon",
    ingredients: ["Vodka", "Blue curacao", "Lemon juice", "Lemon lime soda"],
    price: "160.00",
  },
  {
    imgSrc: "../images/Cocktails/longIsland.png",
    title: "Long island",
    ingredients: [
      "Vodka",
      "White rum",
      "Gin",
      "Tequila",
      "Lemon juice",
      "simple syrup",
      "Coca cola",
    ],
    price: "160.00",
  },
  {
    imgSrc: "../images/Cocktails/jagerita.png",
    title: "Jägerita",
    ingredients: ["Jägermeister", "Triple sec", "Lemon juice", "Simple syrup"],
    price: "180.00",
  },
  {
    imgSrc: "../images/Cocktails/beesKnees.png",
    title: "Bee's knees",
    ingredients: ["Gin", "Lemon juice", "Triple sec", "Honey"],
    price: "160.00",
  },
  {
    imgSrc: "../images/Cocktails/amarettoSour.png",
    title: "Amaretto sour",
    ingredients: ["Amaretto", "Lemon juice", "Simple syrup"],
    price: "180.00",
  },
  {
    imgSrc: "../images/Cocktails/aperolSpritz.png",
    title: "Aperol spritz",
    ingredients: ["Aperol", "White wine", "Soda water"],
    price: "160.00",
  },
  {
    imgSrc: "../images/Cocktails/whiskeySour.png",
    title: "Whiskey sour",
    ingredients: ["Whiskey", "Lemon juice", "Simple syrup"],
    price: "250.00",
  },
];
const others = [
  {
    imgSrc: "../images/Other/Shisha.png",
    mkTitle: "наргиле",
    enTitle: "hookah",
    price: "400.00",
  },
  {
    imgSrc: "../images/Other/Sladoled.png",
    mkTitle: "сладолед",
    enTitle: "ice cream",
    price: "100.00",
  },
  {
    imgSrc: "../images/Other/Apetisani.png",
    mkTitle: "апетисани",
    enTitle: "appetizers",
    price: "100.00",
  },
  {
    imgSrc: "../images/Other/Honey.png",
    mkTitle: "мед",
    enTitle: "honey",
    price: "10.00",
  },
];
